version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: nokogiri
    versions:
    - 1.11.0
    - 1.11.2
  - dependency-name: test-prof
    versions:
    - 0.12.2
    - 1.0.0
    - 1.0.1
  - dependency-name: carrierwave
    versions:
    - 1.3.2
  - dependency-name: rack-attack
    versions:
    - 6.4.0
  - dependency-name: capybara
    versions:
    - 3.35.1
  - dependency-name: brakeman
    versions:
    - 4.10.1
  - dependency-name: rack
    versions:
    - 2.1.4
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: xterm
    versions:
    - 4.10.0
    - 4.9.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: jszip
    versions:
    - 3.5.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
